---

- name: Restart tomcat
  service: state=restarted name={{ tomcat_service_name }}
  tags:
    - tomcat
    - shibboleth

- name: Restart tomcat in docker
  shell: killall -9 java ; systemctl start tomcat8 ; echo
  tags:
    - tomcat
    - shibboleth
